version: '3'

services:
  frontend:
    build:
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=DemoCrud.settings
    volumes:
      - ./backend:/app