# Generated by Django 3.2.25 on 2024-05-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0003_auto_20240406_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWorkManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ayudantes', models.ManyToManyField(blank=True, related_name='obras_ayudante', to='demo_crud.CustomUser')),
                ('capataz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_capataz', to='demo_crud.customuser')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras_dirigidas', to='demo_crud.customuser')),
                ('peones', models.ManyToManyField(blank=True, related_name='obras_peon', to='demo_crud.CustomUser')),
            ],
            options={
                'verbose_name': 'Gestión de Obra',
                'verbose_name_plural': 'Gestiones de Obra',
            },
        ),
    ]
