# Generated by Django 3.2.25 on 2024-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0004_customworkmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customworkmanagement',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('en_desarrollo', 'En Desarrollo'), ('finalizada', 'Finalizada')], default='nueva', max_length=255, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
