# Generated by Django 3.2.25 on 2024-05-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0005_customworkmanagement_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomJobManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('en_desarrollo', 'En Desarrollo'), ('en_revision', 'En Revisión'), ('aceptada', 'Aceptada')], max_length=255, verbose_name='Estado')),
                ('ayudantes', models.ManyToManyField(blank=True, related_name='tareas_ayudante', to='demo_crud.CustomUser')),
                ('capataz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_capataz', to='demo_crud.customuser')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_dirigidas', to='demo_crud.customuser')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_dirigidas', to='demo_crud.customworkmanagement')),
                ('peones', models.ManyToManyField(blank=True, related_name='tareas_peon', to='demo_crud.CustomUser')),
            ],
            options={
                'verbose_name': 'Gestión de Tareas',
                'verbose_name_plural': 'Gestiones de Tarea',
            },
        ),
    ]
