# Generated by Django 3.2.25 on 2024-05-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0007_customworkmanagement_reporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='customjobmanagement',
            name='estareporte',
            field=models.CharField(default='Sin reporte', max_length=255, verbose_name='Reporte'),
            preserve_default=False,
        ),
    ]
