# Generated by Django 3.2.25 on 2024-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0008_customjobmanagement_estareporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customjobmanagement',
            name='estareporte',
            field=models.CharField(max_length=15000, verbose_name='Reporte'),
        ),
    ]
