# Generated by Django 3.2.25 on 2024-06-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0010_remove_customjobmanagement_estareporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='customjobmanagement',
            name='estareporte',
            field=models.CharField(default='None', max_length=15000, verbose_name='Reporte'),
            preserve_default=False,
        ),
    ]
