# Generated by Django 3.2.25 on 2024-06-02 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0011_customjobmanagement_estareporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customjobmanagement',
            old_name='estareporte',
            new_name='reporte',
        ),
    ]
