# Generated by Django 3.2.25 on 2024-06-07 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_crud', '0013_alter_customworkmanagement_reporte'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProgressManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.CharField(max_length=255, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=255, verbose_name='Longitud')),
                ('observaciones', models.CharField(max_length=15000, verbose_name='Observaciones')),
                ('nota_de_voz', models.FileField(blank=True, null=True, upload_to='notas_de_voz/')),
                ('obra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obras', to='demo_crud.customworkmanagement')),
                ('tareas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_obra', to='demo_crud.customjobmanagement')),
            ],
            options={
                'verbose_name': 'Gestión de Progreso',
                'verbose_name_plural': 'Gestiones de Progreso',
            },
        ),
    ]
