"""
Django settings for DemoCrud project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import psycopg2
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5c&o=ie4qmrj&#3m=5-81@zcjrhyb)r9_45#-e31=pqy^99_2n'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'psycopg2',
    'demo_crud',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'DemoCrud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOWED_ORIGINS = [
    "http://34.66.141.23",
    "http://localhost:8080",  # Reemplaza esto con la URL de tu aplicación Vue.js
    "http://localhost:8081",  # Reemplaza esto con la URL de tu aplicación Vue.js
]

WSGI_APPLICATION = 'DemoCrud.wsgi.application'


CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
]

# Opcionalmente, puedes permitir todas las cabeceras:
CORS_ALLOW_HEADERS = '*'

# Otras configuraciones opcionales para CORS

# Permitir todos los métodos HTTP (GET, POST, PUT, DELETE, etc.)
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Si deseas permitir todos los orígenes (útil para desarrollo, no recomendado para producción)
CORS_ALLOW_ALL_ORIGINS = True

# Configuración adicional para permitir credenciales (cookies, headers de autenticación, etc.)
CORS_ALLOW_CREDENTIALS = True


ALLOWED_HOSTS = [
    '34.66.141.23',
    '127.0.0.1',
]


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', # [YOUR - DBNAME]
        'USER' : 'postgres.ehkmcxgesqvmimghlgvw', # [YOUR - USER]
        'PASSWORD' : 'DanielAlan#123456789.', # [YOUR - PASSWORD] en el caso de supabase, password del proyecto
        'HOST' : 'aws-0-us-west-1.pooler.supabase.com', # [YOUR - HOST]
        'PORT' : '5432' # [YOUR - PORT]
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = False

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Para autenticar por nombre de usuario
    'django.contrib.auth.backends.AllowAllUsersModelBackend',  # Para autenticar por correo electrónico
]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
